version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
